name: Check for updates

on:
  schedule:
    - cron: 30 3 * * *
  workflow_dispatch:

jobs:
  setup-versions-from-manifest:
    name: Run cron
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10.12' 
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv
      - name: Run script
        run: pipenv run python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ env.TELEGRAM_CHAT_ID }}
